[package]
name = "noor-notes"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
gtk.workspace = true
sourceview5.workspace = true
gdk4-x11.workspace = true
adw.workspace = true
anyhow.workspace = true
chrono.workspace = true
noor-crypto = { path = "../../crates/crypto" }
noor-domain = { path = "../../crates/domain" }
noor-storage = { path = "../../crates/storage" }
noor-sync = { path = "../../crates/sync" }
noor-windowing = { path = "../../crates/windowing" }
noor-xpad-import = { path = "../../crates/xpad-import" }
tokio.workspace = true
thiserror.workspace = true
oo7.workspace = true
zeroize.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
chrono.workspace = true
tempfile.workspace = true
